import type { Profile } from "./types";

export const defaultProfile: Profile = {
  hero: {
    name: "你的名字",
    title: "AI 探索者 · Vibe Coder",
    avatar: "",
    bio: "热爱 AI 技术，专注于用 AI 工具创造有趣的产品。相信 vibe coding 的力量，用直觉和创造力驱动代码。",
    socialLinks: [
      { platform: "github", url: "https://github.com", icon: "github" },
      { platform: "twitter", url: "https://twitter.com", icon: "twitter" },
      { platform: "email", url: "mailto:hello@example.com", icon: "email" },
    ],
    heroLayout: { x: 0, y: 0, w: 4, h: 4 },
  },
  sections: [
    {
      id: "about-me",
      type: "about",
      title: "关于我",
      visible: true,
      layout: { x: 0, y: 0, w: 6, h: 3, minW: 3, minH: 2 },
      items: [
        {
          id: "about-1",
          type: "text",
          sortOrder: 0,
          content:
            "我是一名 AI 技术爱好者，热衷于探索人工智能在各个领域的应用。\n\n从最初的 ChatGPT 到现在的 Claude、Cursor 等工具，我一直在学习和实践如何更好地与 AI 协作。\n\n我相信 vibe coding — 一种更直觉、更有创造力的编程方式。",
        },
      ],
    },
    {
      id: "work-experience",
      type: "work-experience",
      title: "工作经验",
      visible: true,
      layout: { x: 6, y: 0, w: 6, h: 4, minW: 4, minH: 3 },
      items: [
        {
          id: "work-1",
          type: "work-experience",
          sortOrder: 0,
          company: "示例科技公司",
          companyLogo: "",
          role: "AI 产品经理",
          startDate: "2024-01",
          endDate: null,
          description:
            "负责 AI 产品的规划和落地\n主导多个 AI 自动化项目\n推动团队采用 AI 辅助开发流程",
        },
        {
          id: "work-2",
          type: "work-experience",
          sortOrder: 1,
          company: "创新互联网公司",
          companyLogo: "",
          role: "全栈开发工程师",
          startDate: "2022-06",
          endDate: "2023-12",
          description:
            "使用 React/Node.js 开发 Web 应用\n引入 AI 代码助手提升开发效率\n参与技术选型和架构设计",
        },
      ],
    },
    {
      id: "ai-projects",
      type: "ai-projects",
      title: "AI 项目产出",
      visible: true,
      layout: { x: 0, y: 3, w: 12, h: 3, minW: 4, minH: 2 },
      items: [
        {
          id: "proj-1",
          type: "ai-project",
          sortOrder: 0,
          title: "AI 个人助手",
          screenshot: "",
          description:
            "基于 Claude API 构建的个人知识管理助手，支持自然语言搜索和智能总结。",
          linkUrl: "",
          tags: ["Claude", "Next.js", "AI"],
        },
        {
          id: "proj-2",
          type: "ai-project",
          sortOrder: 1,
          title: "Vibe Coding 作品集",
          screenshot: "",
          description:
            "完全通过 vibe coding 方式构建的个人网站，展示 AI 辅助开发的无限可能。",
          linkUrl: "",
          tags: ["Cursor", "React", "Vibe Coding"],
        },
        {
          id: "proj-3",
          type: "ai-project",
          sortOrder: 2,
          title: "AI 内容生成工具",
          screenshot: "",
          description:
            "利用 GPT-4 批量生成营销文案和社交媒体内容的自动化工具。",
          linkUrl: "",
          tags: ["ChatGPT", "Python", "Automation"],
        },
      ],
    },
    {
      id: "learning-timeline",
      type: "timeline",
      title: "AI 学习历程",
      visible: true,
      layout: { x: 0, y: 6, w: 12, h: 2, minW: 6, minH: 2 },
      items: [
        {
          id: "tl-1",
          type: "timeline-event",
          sortOrder: 0,
          date: "2022-12",
          title: "初次接触 ChatGPT",
          description: "第一次使用 ChatGPT，被 AI 的能力震撼，开始系统学习 Prompt Engineering。",
          image: "",
          category: "milestone",
        },
        {
          id: "tl-2",
          type: "timeline-event",
          sortOrder: 1,
          date: "2023-06",
          title: "深入学习 LLM",
          description: "系统学习大语言模型原理，开始用 API 构建 AI 应用。",
          image: "",
          category: "learning",
        },
        {
          id: "tl-3",
          type: "timeline-event",
          sortOrder: 2,
          date: "2024-01",
          title: "发现 Vibe Coding",
          description: "开始用 Cursor 和 Claude 进行 vibe coding，编程效率大幅提升。",
          image: "",
          category: "milestone",
        },
        {
          id: "tl-4",
          type: "timeline-event",
          sortOrder: 3,
          date: "2024-06",
          title: "构建 AI 产品",
          description: "独立完成多个 AI 驱动的全栈项目，积累实战经验。",
          image: "",
          category: "project",
        },
      ],
    },
    {
      id: "links",
      type: "links",
      title: "找到我",
      visible: true,
      layout: { x: 0, y: 10, w: 4, h: 2, minW: 2, minH: 2 },
      items: [
        {
          id: "link-1",
          type: "link",
          sortOrder: 0,
          label: "GitHub",
          url: "https://github.com",
          platform: "github",
        },
        {
          id: "link-2",
          type: "link",
          sortOrder: 1,
          label: "Twitter / X",
          url: "https://twitter.com",
          platform: "twitter",
        },
        {
          id: "link-3",
          type: "link",
          sortOrder: 2,
          label: "Email",
          url: "mailto:hello@example.com",
          platform: "email",
        },
      ],
    },
  ],
};
